### ISSUE TITLE
White Screen in Silent Cartographer 

### ISSUE THREAD

**Issue by DrMantisTaboggn** [LivingFray/HaloCEVR#11]
When entering the room with the hunters in the objective "Find the main facility security override" the game white screens. Hud is still visible, but I am unable to figure out a workaround.

![OculusScreenshot1732756680](https://github.com/user-attachments/assets/65d65378-37fc-44f5-8d75-e1c788cbe721)

**Comment by albrechtjess** [comment]
Same issue reported here, consider contributing there https://github.com/LivingFray/HaloCEVR/issues/8
