### ISSUE TITLE
Can't select any option in the main menu

### ISSUE THREAD

**Issue by Manu270891** [LivingFray/HaloCEVR#12]
The game launches and I can see the main menu, and while the laser pointer works, the trigger does not work and I can't select any option. I'm using a Quest 3 with Virtual Desktop with the spanish retail version of Halo with Chimera. I also changed the Chimera settings file as described in the readme.

**Comment by GeekyGami** [comment]
Try going through Quest Link instead.
I've heard tell this works fine.

**Comment by HoriZonUK** [comment]
Have to focus the game first click anywhere on the game screen with your mouse while in VR.

**Comment by Manu270891** [comment]
It works! Thanks!
