### ISSUE TITLE
Feature request: motion controlled manual reloading

### ISSUE THREAD

**Issue by Rainy101** [LivingFray/HaloCEVR#13]
i know this is a big ask and this mods already fantisc but motion controlled manual reloading would just make it even better it just dont feel like a vr shooter if i cant reload the guns with my onw hands

**Comment by HoriZonUK** [comment]
I’m sure its on the guys mind but give them time.

**Comment by LivingFray** [comment]
Sorry, almost certainly not going to happen. The extent of my "animation" capabilities is mangling the view model to track your hands. I can't fundementally alter how gun reloading animations are played/affect the ammo count, its beyond my abilities.
