### ISSUE TITLE
Feature Request: Toggle Head View Locomotion

### ISSUE THREAD

**Issue by voidvoidvoid** [LivingFray/HaloCEVR#18]
Incredible mod! Thank you, I have wanted to play this in VR for years.

Is it possible to add an option to choose between "head look" steering for locomotion control? Most VR games have an option to disable this, and it seems to be enabled by default here. It would make the game more comfortable for people like me who dislike head steering. I don't see anything in the config to control this.

Thanks again for the awesome mod.

**Comment by LivingFray** [comment]
@codyherzog has very kindly submitted a pull request for this (#39) which I have included in release 1.1.0
