### ISSUE TITLE
Feature Request: Independent Left Hand / Right Hand Melee Options

### ISSUE THREAD

**Issue by voidvoidvoid** [LivingFray/HaloCEVR#19]
Is it possible to get options to independently control left and right hand melee attack motion thresholds? When using two-handed grips, I usually trigger an accidental melee attack by going from an "at rest" position with my non-dominant hand at my waist to a two-handed grip position. Being able to set the hand melee sensitivities separately would allow me to make my dominant hand the only melee input, solving this issue.

**Comment by LivingFray** [comment]
Added in 1.1.0
