### ISSUE TITLE
[REQUEST] Enable Two-Handed Grip only when both hands are close to the weapon

### ISSUE THREAD

**Issue by HexHyte** [LivingFray/HaloCEVR#22]
I think the two-handed weapon mode should only activate if the player has both hands near the weapon (or more likely: close to the front of the right hand).
Currently, a slight grip on the left controller (i am using Valve Knuckle controllers) is enough to enter the two-handed mode no matter where my hand is located at that moment, this causes uncomfortable effects such as the weapon moving rapidly in weird directions.
With this change, i could comfortably grip my left controller without worrying about accidentally enabling two-handed mode.

**Comment by teddybear082** [comment]
Someone (I think it was markomon) said in steam you can rebind grips to use force or something so its not triggering accidentally.  Check discord.

**Comment by HexHyte** [comment]
Well, thank you for the tip, your solution should help while a proper fix is being developed, hopefully

**Comment by LivingFray** [comment]
I've added a setting for this in 1.2.0. It checks the distance between the hands rather than proximity to the weapon, because the former is more complicated. Default maximum distance is 0.8m
