### ISSUE TITLE
PLEASE STOP WITH FEATURE REQUESTS (Until further notice from mod author)

### ISSUE THREAD

**Issue by teddybear082** [LivingFray/HaloCEVR#24]
Mod author said in discord when dropping the mod release that they worked for over a year on the mod and got burned out trying to add more features / do more bug fixing so unless you are willing to learn how to implement the feature you are requesting (since mod is open source) please stop with the feature requests so we can let the mod author breathe for a bit.  

![image](https://github.com/user-attachments/assets/76fabb4e-69c4-431f-bd31-834b7fe80724)

If I am wrong about this mod author can feel free to close this issue.

**Comment by HexHyte** [comment]
Can you share the discord server that is being used?
It's the second time a user quoted the server but I can't find which one

**Comment by teddybear082** [comment]
> Can you share the discord server that is being used? It's the second time a user mentioned the ds server but I can't find which one

https://discord.gg/flat2vr

**Comment by teddybear082** [comment]
Closing this as now others are contributing fixes to the mod and documentation so feature requests might be addressed by other contributors without seeming like everyone is just begging LivingFray to make new improvements to the mod.
