### ISSUE TITLE
White void in The Silent Cartographer

### ISSUE THREAD

**Issue by fatmegaman** [LivingFray/HaloCEVR#44]
Quest 3
Happened in both Virtual Desktop and Steam Link
https://youtube.com/shorts/zK4vLt_L8Eg?feature=share

The image goes white in the arena with the two hunters in The Silent Cartographer.  Sometimes it can only happen in one of the lenses. In the video I attached, it switches between happening in both lenses and just the right lens, which is why some of the footage seems okay as it only recorded the left one.  I could also see a colored curved screen in the void. The isssue was not resolved after restarting the game.

**Comment by Charliyo** [comment]
Are you running latest version? The rush update fixed this for me

**Comment by fatmegaman** [comment]
> Are you running latest version? The rush update fixed this for me
I must have downloaded the mod right before the update release. Had no idea there was an update. Thank you.
