### ISSUE TITLE
VR config.txt not generating upon launch

### ISSUE THREAD

**Issue by jodelejb** [LivingFray/HaloCEVR#45]
Tried both the initial release version and 1.1.0 and neither appears to be generating a config file in the VR directory.

**Comment by DrBombinator** [comment]
Did Halo get installed into Program Files (x86)? By default it goes there, which is admin-protected.  You can probably get around it by running Halo as administrator, but it was causing enough problems that I just moved it to a different directory.

**Comment by jodelejb** [comment]
You are absolutely right. Thanks for the tip! moving it outside of that directory solved the issue for me.
