### ISSUE TITLE
config.txt not getting generated.

### ISSUE THREAD

**Issue by Sgtmoustache** [LivingFray/HaloCEVR#48]
Hi! 

I got it working properly but I don't have any config.txt file getting generated.

I'm left handed so I can't switch the mode.
Is it possible to simply create it manually instead?

Thanks a lot for this very cool mod!

**Comment by 97saundersj** [comment]
As far as I know it should just be created when you run the mod for the first time. What files do you have inside the vr file in the halo game directory?

**Comment by Sgtmoustache** [comment]
In the VR directory, I only have the OpenVR folder. Inside of it, I have this :

![image](https://github.com/user-attachments/assets/d8714f9e-d0fc-456f-bd6d-fec0cb5c528b)

**Comment by LivingFray** [comment]
If the game is installed in program files halo.exe needs to be run as admin to be able to generate the config file. Your options are:
1. Run as admin
2. Reinstall the game in a different (non-protected) directory
3. Manually save out a copy of the config file in the VR directory (not the OpenVR sub folder) (make sure to run your text editor as admin or it won't be able to save the file either!)

I'd recommend option 2 as this will mean you don't have to mess with admin privileges and the game will also be able to generate its log file should anything else go wrong.
