### ISSUE TITLE
VR_init Failed

### ISSUE THREAD

**Issue by Reaper138** [LivingFray/HaloCEVR#52]
[OpenVR] VR_Init failed: installation path could not be located (110)

any idea how to fix that?

Windows 11, Occulus Quest 2

**Comment by ralstig** [comment]
Run it as admin.
(Read the install instructions and known issues)

**Comment by Reaper138** [comment]
Got it solved once I figured out how to run quest link and steam vr at the
same time.
Respectfully,
Matt Allen

**Comment by teddybear082** [comment]
Please close the issue as this was not an issue with the mod.
