### ISSUE TITLE
Segmentation Fault crash on launch

### ISSUE THREAD

**Issue by t3hm00kz** [LivingFray/HaloCEVR#59]
Segmentation fault on launch.

ENVIRONMENT:
W10 Pro 64-bit
128GB Dual Channel DDR4

Monitors:
VG248
Cintiq 13HD
LCD2690WUXi

CPU: Intel Core i7@ 3.70GHz (I7-8700k)
GPU: Gefore GTX 1080Ti

NVidea Driver Version: 566.14

Installation Environment:
Fresh install to P:\Program Files (x86)\Games\Microsoft Games\Halo
Patch 1.10 applied
Chimera 1.0.0r1021.10144368 applied
Halo VR version 1.1.0 

System Font disabled

REPRO STEPS:
1. Fresh install Halo PC (English) from ISO
2. Install patch 1.10
3. Launch game to generate inits
4. Install Chimera 1.0.0r1021.10144368 
5. Launch game to generate inits
6. Apply Halo VR version 1.1.0
7. Launch Meta Quest Link
8. Launch Steam VR
9. Launch Halo

EXPECTED:
Halo PC launches in VR

ACTUAL:
Halo PC crashes to "The game has encountered a segmentation fault."

REPRO RATE:
100%

NOTES:
Tested on both Custom Edition and PC fresh installs with 1.10/Chimera applied.
Video and Screenshot attached.

![vlcsnap-2024-12-03-01h55m46s197](https://github.com/user-attachments/assets/42cf38b5-8905-4b69-9621-900738a205d4)

https://github.com/user-attachments/assets/885b5da6-c29f-4daa-91b8-f90644042006

**Comment by t3hm00kz** [comment]
Regenerating my Chimera settings in "My Documents/My Games/Halo/Chimera" fixed the issue.

**Comment by HoriZonUK** [comment]
Try not installing to \Program Files (x86) it causes issues.

**Comment by teddybear082** [comment]
Glad you got it working. Please close this issue as this was user error (installing in programfiles) and/or your system issue not an issue with the mod.

**Comment by t3hm00kz** [comment]
closing as user error.

if anybody gets a Segmentation Fault on launch, it may be the Chimera directory in My Documents.
