### ISSUE TITLE
Upon launch the menus are weirdly scaled, UI text is missing in the menu buttons. Is this a resolution problem? Chimera related?

### ISSUE THREAD

**Issue by rickchain** [LivingFray/HaloCEVR#75]
As soon as I click campaign to start, all the menus are scaled way bigger than they should be. I can't seem to figure out why. It means I'm unable to get into the campaign or any modes. 

I installed Chimera prior. 

I also have a widescreen monitor, which could be an issue?

**Comment by LivingFray** [comment]
Did you disable the font settings in chimera as per the installation guide?
