### ISSUE TITLE
Silent cartographer whitescreen

### ISSUE THREAD

**Issue by Amyharrison93** [LivingFray/HaloCEVR#8]
after the two hunters in the silent cartographer mission, if i enter the structure and go down the ramp the game white screens. i can fix the white screen by changing the video settings but when i do i get an error reading: "this game has encountered a segmentation fault"

**Comment by DrMantisTaboggn** [comment]
Same issue

**Comment by s-ilent** [comment]
Me too!

**Comment by kitaaaaaa** [comment]
if you run the game with -useff, the screen effect no longer appears. of course the game looks terrible at that point but you can get past it. it appears to be a chapter transition effect so it will probably happen on nearly every map.

**Comment by instantkarma56** [comment]
Same problem here, game not playable past silent cartographer. Psvr2 user btw

**Comment by Dragonslayer182** [comment]
So I managed to get the white right eye glitch. I played for a few seconds, got to the elite at the console, and the game crashed with a segmentation fault. 

To cause this, I first got the white screen from the "Shafted" cutscene (Chief kicks a rock off the ledge), exited the game, ran the game in Fixed Function (-useff) mode to play the cutscene normally, and then switched back to the normal mode once the post-checkpoint cutscene played. This is when the white right eye and segfault crash happened. I also noticed that the level textures in-game were going missing and possibly glitching out as well.

I am using a Valve Index, with a 7800x3d CPU and 1080ti GPU running Windows 10 22H2. I am using Chimera with Halo.

![image](https://github.com/user-attachments/assets/cb05d00a-aaf1-4d9f-8e57-11b10c4524a2)

**Comment by BOLL7708** [comment]
Hello, I experienced the same issue, reloaded the game twice, still happened every time I went down to the two indoor hunters in the Silent Cartographer. (Side note, awesome work on this mod, enjoying it a lot as an old Halo fanatic, thanks for making this, cheers!)

**Comment by LivingFray** [comment]
Should be fixed in release 1.0.1. I haven't had much time to test it so let me know if its still an issue.
