### ISSUE TITLE
The Silent Cartographer Issue

### ISSUE THREAD

**Issue by Slimybirch** [LivingFray/HaloCEVR#80]
Whenever I get into the second underground portion after entering the tunnel and taking the first left, after a few feet everything but the UI goes white. Reloading a save doesn't work, reloading the .map file doesn't work, quitting the session doesn't work as once this happens, anything rendered, even on the main menu is now white except for the UI. Only closing the game and reopening fixes it but once I hit that area again, it goes back to white.

**Comment by LivingFray** [comment]
Are you using the latest version of the mod? This should have been patched in version 1.0.1

**Comment by Slimybirch** [comment]
Oh snap! I am not! I will try that ASAP. Thank you!

**Comment by teddybear082** [comment]
please close the issue as dev would assume folks always have the most updated version of the mod.  :)

**Comment by Slimybirch** [comment]
Running updated version fixed issue
